default: &default
  adapter: postgresql
  user: postgres
  password:
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: elysium_models_development

test:
  <<: *default
  database: elysium_models_test
